apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc
  labels:
    app: post-api
    tier: application
spec:
  type: NodePort
  selector:
    app: post-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080